#import "TakeoffAnalysisConfig.h"
#import <UIKit/UIKit.h>

static NSString * const MTJudgeTakeoffConfigsKey = @"MTJudge.TakeoffAnalysisConfigs";

@implementation TakeoffAnalysisConfig
+ (BOOL)supportsSecureCoding { return YES; }
- (instancetype)init { if ((self = [super init])) { _rampPointA = CGPointMake(NAN, NAN); _rampPointB = CGPointMake(NAN, NAN); _lipPoint = CGPointMake(NAN, NAN); _takeoffStartTime = kCMTimeInvalid; _lipExitTime = kCMTimeInvalid; _analysisSide = TakeoffAnalysisSideAuto; } return self; }
- (void)encodeWithCoder:(NSCoder *)coder { [coder encodeObject:self.videoIdentifier forKey:@"videoIdentifier"]; [coder encodeObject:NSStringFromCGPoint(self.rampPointA) forKey:@"rampPointA"]; [coder encodeObject:NSStringFromCGPoint(self.rampPointB) forKey:@"rampPointB"]; [coder encodeObject:NSStringFromCGPoint(self.lipPoint) forKey:@"lipPoint"]; [coder encodeInt64:self.takeoffStartTime.value forKey:@"startValue"]; [coder encodeInt32:self.takeoffStartTime.timescale forKey:@"startScale"]; [coder encodeInt64:self.lipExitTime.value forKey:@"exitValue"]; [coder encodeInt32:self.lipExitTime.timescale forKey:@"exitScale"]; [coder encodeInteger:self.analysisSide forKey:@"analysisSide"]; [coder encodeBool:self.enabled forKey:@"enabled"]; }
- (instancetype)initWithCoder:(NSCoder *)coder { if ((self = [self init])) { _videoIdentifier = [coder decodeObjectOfClass:NSString.class forKey:@"videoIdentifier"]; _rampPointA = CGPointFromString([coder decodeObjectOfClass:NSString.class forKey:@"rampPointA"] ?: NSStringFromCGPoint(CGPointMake(NAN, NAN))); _rampPointB = CGPointFromString([coder decodeObjectOfClass:NSString.class forKey:@"rampPointB"] ?: NSStringFromCGPoint(CGPointMake(NAN, NAN))); _lipPoint = CGPointFromString([coder decodeObjectOfClass:NSString.class forKey:@"lipPoint"] ?: NSStringFromCGPoint(CGPointMake(NAN, NAN))); int32_t startScale = [coder decodeInt32ForKey:@"startScale"]; int32_t exitScale = [coder decodeInt32ForKey:@"exitScale"]; _takeoffStartTime = CMTimeMake([coder decodeInt64ForKey:@"startValue"], startScale > 0 ? startScale : 600); _lipExitTime = CMTimeMake([coder decodeInt64ForKey:@"exitValue"], exitScale > 0 ? exitScale : 600); _analysisSide = [coder decodeIntegerForKey:@"analysisSide"]; _enabled = [coder decodeBoolForKey:@"enabled"]; } return self; }
+ (instancetype)configForVideoURL:(NSURL *)url { NSString *key = url.lastPathComponent ?: @""; NSDictionary *stored = [[NSUserDefaults standardUserDefaults] dictionaryForKey:MTJudgeTakeoffConfigsKey][key]; if (!stored) { TakeoffAnalysisConfig *config = [self new]; config.videoIdentifier = key; return config; } NSData *data = [NSKeyedArchiver archivedDataWithRootObject:stored requiringSecureCoding:NO error:NULL]; (void)data; TakeoffAnalysisConfig *config = [self new]; config.videoIdentifier = key; if ([stored[@"start"] isKindOfClass:NSNumber.class]) config.takeoffStartTime = CMTimeMakeWithSeconds([stored[@"start"] doubleValue], 600); if ([stored[@"exit"] isKindOfClass:NSNumber.class]) config.lipExitTime = CMTimeMakeWithSeconds([stored[@"exit"] doubleValue], 600); config.rampPointA = CGPointMake([stored[@"ax"] doubleValue], [stored[@"ay"] doubleValue]); config.rampPointB = CGPointMake([stored[@"bx"] doubleValue], [stored[@"by"] doubleValue]); config.lipPoint = CGPointMake([stored[@"lx"] doubleValue], [stored[@"ly"] doubleValue]); config.analysisSide = [stored[@"side"] integerValue]; config.enabled = [stored[@"enabled"] boolValue]; return config; }
- (void)save { if (!self.videoIdentifier.length) return; NSMutableDictionary *all = [[[NSUserDefaults standardUserDefaults] dictionaryForKey:MTJudgeTakeoffConfigsKey] mutableCopy] ?: [NSMutableDictionary dictionary]; all[self.videoIdentifier] = @{ @"ax": @(self.rampPointA.x), @"ay": @(self.rampPointA.y), @"bx": @(self.rampPointB.x), @"by": @(self.rampPointB.y), @"lx": @(self.lipPoint.x), @"ly": @(self.lipPoint.y), @"start": @(CMTimeGetSeconds(self.takeoffStartTime)), @"exit": @(CMTimeGetSeconds(self.lipExitTime)), @"side": @(self.analysisSide), @"enabled": @(self.enabled) }; [[NSUserDefaults standardUserDefaults] setObject:all forKey:MTJudgeTakeoffConfigsKey]; }
@end
